# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ApolloRX2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ApolloRX2

  pod 'Parse'
  pod 'AlamofireImage'

  target 'ApolloRX2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ApolloRX2UITests' do
    # Pods for testing
  end

end
